### ISSUE TITLE
hacer que los botones del menú funcionen

### ISSUE THREAD

**Issue by MiguelAVSG** [MiguelAVSG/TheBattleOfSurvival#1]
si escoge el botón de play que pase a una pantalla vació
si escoge el botón de instrucciones que pase a una pantalla con instrucciones
si escoge el botón de récords que muestre una pantalla de récords
si escoge el botón de salir que salga del juego.

**Comment by iuresti** [comment]
Excelente descripción del issue... creo que queda claro perfectamente lo que se espera al resolver este ticket
