### ISSUE TITLE
Crear la pantalla de records

### ISSUE THREAD

**Issue by MiguelAVSG** [MiguelAVSG/TheBattleOfSurvival#3]
Que la pantalla pueda guardar récords del jugador y ponerlos de el récord con mayor puntaje al mas pequeño con un tamaño de 10 records

**Comment by iuresti** [comment]
La descripción es un poco confusa.. en realidad la pantalla de records no debe "guardar" nada .. este ticket podría describir de dónde se van a leer los records del juego (por ejemplo cómo se llama el archivo y en qué ruta está) además de describir el formato del archivo.. entonces cualquiera que tome el ticket podría saber que debe abrir un archivo y cómo leerlo

**Comment by MiguelAVSG** [comment]
creara un archivo de texto el cual contenga los récords de los jugadores con puntuación mas alta que a su vez se pueda abrir el archivo para consultarlos
