### ISSUE TITLE
Hacer que el player salte

### ISSUE THREAD

**Issue by DiegoDiazDeLeon** [MiguelAVSG/TheBattleOfSurvival#4]
hay que hacer que el mointo salte y tenga otra animacion al saltar

**Comment by iuresti** [comment]
Aunque la descripción es clara en cuanto a qué se espera, alguien que no esté involucrado en el proyecto no sabría ni por dónde empezar... podrías añadir en la descripción qué clase representa el "monito" al que haces referencia
